const { exec } = require('child_process');
const fs = require('fs');
const path = require('path');
const Replicate = require('replicate');

// Bundled static ffmpeg binary — works both locally and inside Vercel's
// serverless (Lambda) runtime, where there is no system-installed ffmpeg.
let ffmpegBinaryPath = 'ffmpeg';
try {
  ffmpegBinaryPath = require('ffmpeg-static');
} catch (e) {
  console.warn('ffmpeg-static not found, falling back to system "ffmpeg" on PATH.');
}

// Helper to run shell commands (FFmpeg)
const runCommand = (command) => {
  return new Promise((resolve, reject) => {
    console.log(`Executing: ${command}`);
    exec(command, { maxBuffer: 1024 * 1024 * 20 }, (error, stdout, stderr) => {
      if (error) {
        console.error(`Exec error: ${error.message}`);
        console.error(`Stderr: ${stderr}`);
        reject(error);
      } else {
        resolve(stdout);
      }
    });
  });
};

// Check if FFmpeg is available (bundled binary or system PATH)
const checkFFmpeg = () => {
  return new Promise((resolve) => {
    exec(`"${ffmpegBinaryPath}" -version`, (error) => {
      if (error) {
        console.warn('WARNING: FFmpeg is not available. Local video generation will fallback to mock video.');
        resolve(false);
      } else {
        resolve(true);
      }
    });
  });
};

/**
 * Generate Local Video using FFmpeg
 * Overlays frame on photo with Ken Burns zoom effect and audio (if available)
 */
const generateLocalVideo = async (photoPath, framePath, outputPath, audioPath = null) => {
  const hasFFmpeg = await checkFFmpeg();
  if (!hasFFmpeg) {
    // If FFmpeg is missing, copy photo to output file as a mock video placeholder
    console.log('Falling back to Mock Video generation because FFmpeg is missing...');
    // In a real scenario, we can create a simple copy, or write a dummy file
    // Let's copy a dummy file or the photo itself.
    // If we want a valid MP4 but FFmpeg is missing, we'll just write a mock file.
    // To make sure it has a valid extension, we will just copy the photo or write a small mock binary
    // so that the frontend doesn't crash on download. 
    // Ideally, the user will install FFmpeg. We will write a clear message in server logs.
    fs.copyFileSync(photoPath, outputPath);
    return;
  }

  // Ensure output directory exists
  const outputDir = path.dirname(outputPath);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  // FFmpeg Zoom and Overlay Command
  // 1. Loops the input photo for 5 seconds (-loop 1 -t 5)
  // 2. Applies scale and zoompan to zoom in from center
  // 3. Overlays the transparent frame PNG
  // 4. Adds background music (if provided and exists)
  
  let cmd = '';
  if (audioPath && fs.existsSync(audioPath)) {
    cmd = `"${ffmpegBinaryPath}" -y -loop 1 -i "${photoPath}" -i "${framePath}" -i "${audioPath}" -filter_complex "[0:v]scale=1080:1920,zoompan=z='zoom+0.0015':d=150:s=1080x1920:x='iw/2-(iw/zoom/2)':y='ih/2-(ih/zoom/2)'[bg]; [bg][1:v]overlay=0:0[outv]" -map "[outv]" -map 2:a -c:v libx264 -t 5 -pix_fmt yuv420p -shortest "${outputPath}"`;
  } else {
    // Silent video
    cmd = `"${ffmpegBinaryPath}" -y -loop 1 -i "${photoPath}" -i "${framePath}" -filter_complex "[0:v]scale=1080:1920,zoompan=z='zoom+0.0015':d=150:s=1080x1920:x='iw/2-(iw/zoom/2)':y='ih/2-(ih/zoom/2)'[bg]; [bg][1:v]overlay=0:0" -c:v libx264 -t 5 -pix_fmt yuv420p "${outputPath}"`;
  }

  await runCommand(cmd);
  console.log(`Local video generated successfully at ${outputPath}`);
};

/**
 * Generate AI Video using Replicate SVD
 */
const generateAIVideo = async (photoUrl, framePath, outputPath, replicateToken) => {
  if (!replicateToken) {
    throw new Error('Replicate API Token is missing in .env config.');
  }

  const replicate = new Replicate({
    auth: replicateToken,
  });

  console.log('Sending photo to Replicate Stable Video Diffusion API...');
  
  // Stable Video Diffusion model
  const model = 'stability-ai/stable-video-diffusion:3f04bca0b24772fb27076bf24a4c23d00be741167077e36688b1ed499edec5a4';
  const prediction = await replicate.run(model, {
    input: {
      image: photoUrl,
      video_length: '14_frames_with_svd_xt',
      sizing_strategy: 'keep_input_size',
      frames_per_second: 6,
      motion_bucket_id: 127,
      cond_aug: 0.02,
      decoding_t: 7
    }
  });

  // Replicate returns video URL (usually WebM or MP4)
  const aiVideoUrl = prediction[0] || prediction;
  if (!aiVideoUrl) {
    throw new Error('Failed to get video URL from Replicate.');
  }

  console.log(`AI video generated by Replicate: ${aiVideoUrl}`);

  // Download the AI video locally
  const tempAiVideoPath = path.join(path.dirname(outputPath), `temp_ai_${Date.now()}.mp4`);
  
  const response = await fetch(aiVideoUrl);
  const buffer = await response.arrayBuffer();
  fs.writeFileSync(tempAiVideoPath, Buffer.from(buffer));

  const hasFFmpeg = await checkFFmpeg();
  if (hasFFmpeg) {
    // Overlay the frame PNG on the AI generated video
    // AI video might be landscape or small, so we scale it to fit 1080x1920 and then overlay frame
    const cmd = `"${ffmpegBinaryPath}" -y -i "${tempAiVideoPath}" -i "${framePath}" -filter_complex "[0:v]scale=1080:1920[bg]; [bg][1:v]overlay=0:0" -c:v libx264 -pix_fmt yuv420p "${outputPath}"`;
    await runCommand(cmd);
    
    // Clean up temp file
    try {
      fs.unlinkSync(tempAiVideoPath);
    } catch (e) {
      console.warn('Error deleting temp AI video:', e);
    }
  } else {
    // If no FFmpeg, rename temp video directly to output path
    fs.renameSync(tempAiVideoPath, outputPath);
  }

  console.log(`AI video compilation complete: ${outputPath}`);
};

module.exports = {
  generateLocalVideo,
  generateAIVideo,
  checkFFmpeg,
};
